import FWCore.ParameterSet.Config as cms

externalLHEProducer = cms.EDProducer("ExternalLHEProducer",
#    args = cms.vstring('/cvmfs/cms.cern.ch/phys_generator/gridpacks/2017/13TeV/powheg/V2/TT_hvq/TT_hdamp_NNPDF31_NNLO_dilepton.tgz'),
    args = cms.vstring('/afs/cern.ch/work/k/kaho/CMSSW_10_6_24/src/test/test.tgz'),
    nEvents = cms.untracked.uint32(5000),
    numberOfParameters = cms.uint32(1),
    outputFile = cms.string('cmsgrid_final.lhe'),
    scriptName = cms.FileInPath('GeneratorInterface/LHEInterface/data/run_generic_tarball_cvmfs.sh')
)

from Configuration.Generator.Herwig7Settings.Herwig7LHECommonSettings_cfi import *
from Configuration.Generator.Herwig7Settings.Herwig7StableParticlesForDetector_cfi import *
from Configuration.Generator.Herwig7Settings.Herwig7CH3TuneSettings_cfi import *
from Configuration.Generator.Herwig7Settings.Herwig7LHEPowhegSettings_cfi import *
from Configuration.Generator.Herwig7Settings.Herwig7PSWeightsSettings_cfi import *
from Configuration.Generator.Herwig7Settings.Herwig7_7p1SettingsFor7p2_cfi import *

generator = cms.EDFilter("Herwig7GeneratorFilter",
    herwig7LHECommonSettingsBlock,
    herwig7LHEPowhegSettingsBlock,
    herwig7p1SettingsFor7p2Block,
    herwig7StableParticlesForDetectorBlock,
    herwig7PSWeightsSettingsBlock,
    herwig7CH3SettingsBlock,
    configFiles = cms.vstring(),
    crossSection = cms.untracked.double(-1),
    dataLocation = cms.string('${HERWIGPATH:-6}'),
    eventHandlers = cms.string('/Herwig/EventHandlers'),
    filterEfficiency = cms.untracked.double(1.0),
    generatorModule = cms.string('/Herwig/Generators/EventGenerator'),   
    hw_lhe_common_settings_custom = cms.vstring(
        'cd /Herwig/Shower', 
        'set AlphaQCD:AlphaIn 0.118', 
        'cd /',
        'cd /Herwig/EventHandlers', 
        'library LesHouches.so', 
        'create ThePEG::LesHouchesEventHandler LesHouchesHandler', 
        'set LesHouchesHandler:PartonExtractor /Herwig/Partons/PPExtractor', 
        'set LesHouchesHandler:CascadeHandler /Herwig/DipoleShower/DipoleShowerHandler', 
        'set LesHouchesHandler:DecayHandler /Herwig/Decays/DecayHandler', 
        'set LesHouchesHandler:HadronizationHandler /Herwig/Hadronization/ClusterHadHandler', 
        'set LesHouchesHandler:WeightOption VarNegWeight', 
        'set /Herwig/Generators/EventGenerator:EventHandler /Herwig/EventHandlers/LesHouchesHandler', 
        'create ThePEG::Cuts /Herwig/Cuts/NoCuts', 
        'create ThePEG::LHAPDF /Herwig/Partons/LHAPDF ThePEGLHAPDF.so', 
        'set /Herwig/Partons/LHAPDF:PDFName NNPDF31_nnlo_as_0118', 
        'set /Herwig/Partons/LHAPDF:RemnantHandler /Herwig/Partons/HadronRemnants', 
        'set /Herwig/Particles/p+:PDF /Herwig/Partons/LHAPDF', 
        'set /Herwig/Particles/pbar-:PDF /Herwig/Partons/LHAPDF', 
        'set /Herwig/Partons/PPExtractor:FirstPDF  /Herwig/Partons/LHAPDF', 
        'set /Herwig/Partons/PPExtractor:SecondPDF /Herwig/Partons/LHAPDF', 
        'create ThePEG::LesHouchesFileReader LesHouchesReader', 
        'set LesHouchesReader:FileName cmsgrid_final.lhe', 
        'set LesHouchesReader:AllowedToReOpen No', 
        'set LesHouchesReader:InitPDFs 0', 
        'set LesHouchesReader:Cuts /Herwig/Cuts/NoCuts', 
        'set LesHouchesReader:MomentumTreatment RescaleEnergy', 
        'set LesHouchesReader:PDFA /Herwig/Partons/LHAPDF', 
        'set LesHouchesReader:PDFB /Herwig/Partons/LHAPDF', 
        'insert LesHouchesHandler:LesHouchesReaders 0 LesHouchesReader', 
        'set /Herwig/DipoleShower/DipoleShowerHandler:MaxPtIsMuF Yes', 
        'set /Herwig/DipoleShower/DipoleShowerHandler:RestrictPhasespace Yes', 
    ),
    herwig7CH3PDF_custom = cms.vstring(
        'cd /Herwig/Partons', 
        'create ThePEG::LHAPDF PDFSet_nnlo ThePEGLHAPDF.so', 
        'set PDFSet_nnlo:PDFName NNPDF31_nnlo_as_0118.LHgrid', 
        'set PDFSet_nnlo:RemnantHandler HadronRemnants', 
        'set /Herwig/Particles/p+:PDF PDFSet_nnlo', 
        'set /Herwig/Particles/pbar-:PDF PDFSet_nnlo', 
        'set /Herwig/Partons/PPExtractor:FirstPDF  PDFSet_nnlo', 
        'set /Herwig/Partons/PPExtractor:SecondPDF PDFSet_nnlo', 
        'set /Herwig/DipoleShower/DipoleShowerHandler:PDFA PDFSet_nnlo', 
        'set /Herwig/DipoleShower/DipoleShowerHandler:PDFB PDFSet_nnlo', 
        'create ThePEG::LHAPDF PDFSet_lo ThePEGLHAPDF.so', 
        'set PDFSet_lo:PDFName NNPDF31_lo_as_0130.LHgrid', 
        'set PDFSet_lo:RemnantHandler HadronRemnants', 
        'set /Herwig/DipoleShower/DipoleShowerHandler:PDFARemnant PDFSet_lo', 
        'set /Herwig/DipoleShower/DipoleShowerHandler:PDFBRemnant PDFSet_lo', 
        'set /Herwig/Partons/MPIExtractor:FirstPDF PDFSet_lo', 
        'set /Herwig/Partons/MPIExtractor:SecondPDF PDFSet_lo', 
        'cd /'
    ),
    hw_PSWeights_settings_custom = cms.vstring(
        'cd /', 
        'cd /Herwig/DipoleShower', 
        'do DipoleShowerHandler:AddVariation RedHighAll 1.141 1.141  All', 
        'do DipoleShowerHandler:AddVariation RedLowAll 0.707 0.707 All', 
        'do DipoleShowerHandler:AddVariation DefHighAll 2 2 All', 
        'do DipoleShowerHandler:AddVariation DefLowAll 0.5 0.5 All', 
        'do DipoleShowerHandler:AddVariation ConHighAll 4 4 All', 
        'do DipoleShowerHandler:AddVariation ConLowAll 0.25 0.25 All', 
        'do DipoleShowerHandler:AddVariation RedHighHard 1.141 1.141  Hard', 
        'do DipoleShowerHandler:AddVariation RedLowHard 0.707 0.707 Hard', 
        'do DipoleShowerHandler:AddVariation DefHighHard 2 2 Hard', 
        'do DipoleShowerHandler:AddVariation DefLowHard 0.5 0.5 Hard', 
        'do DipoleShowerHandler:AddVariation ConHighHard 4 4 Hard', 
        'do DipoleShowerHandler:AddVariation ConLowHard 0.25 0.25 Hard', 
        'do DipoleShowerHandler:AddVariation RedHighSecondary 1.141 1.141  Secondary', 
        'do DipoleShowerHandler:AddVariation RedLowSecondary 0.707 0.707 Secondary', 
        'do DipoleShowerHandler:AddVariation DefHighSecondary 2 2 Secondary', 
        'do DipoleShowerHandler:AddVariation DefLowSecondary 0.5 0.5 Secondary', 
        'do DipoleShowerHandler:AddVariation ConHighSecondary 4 4 Secondary', 
        'do DipoleShowerHandler:AddVariation ConLowSecondary 0.25 0.25 Secondary', 
        'set DipoleShowerHandler:Detuning 2.0', 
        'cd /'
    ),
    hw_user_settings = cms.vstring(
        'cd /Herwig/EventHandlers',
        'set EventHandler:LuminosityFunction:Energy 13000*GeV',
        'cd /Herwig/Particles',
        'do t:SelectDecayModes t->nu_mu,mu+,b; t->nu_e,e+,b;',
        'do tbar:SelectDecayModes tbar->nu_mubar,mu-,bbar; tbar->nu_ebar,e-,bbar;',
        'set h0:NominalMass 125.0',
        'set d:NominalMass 0*GeV',
        'set dbar:NominalMass 0*GeV',
        'set u:NominalMass 0*GeV',
        'set ubar:NominalMass 0*GeV',
        'set s:NominalMass 0*GeV',
        'set sbar:NominalMass 0*GeV',
        'set c:NominalMass 0*GeV',
        'set cbar:NominalMass 0*GeV',
        'set b:NominalMass 0*GeV',
        'set bbar:NominalMass 0*GeV',
        'cd /Herwig/DipoleShower/Kernels',
        'set IFgx2bbbarxDipoleKernel:UseKernel Yes',
        'set IFgx2bbarbxDipoleKernel:UseKernel Yes',
        'set IFMgx2bbbarxDipoleKernel:UseKernel Yes',
        'set IFMgx2bbarbxDipoleKernel:UseKernel Yes',
        'set IIgx2bbbarxDipoleKernel:UseKernel Yes',
        'set IIgx2bbarbxDipoleKernel:UseKernel Yes',
    ),     
    parameterSets = cms.vstring(
        'hw_lhe_common_settings_custom',
        'hw_lhe_powheg_settings',
        'hw_7p1SettingsFor7p2',
        'herwig7CH3PDF_custom', 
        'herwig7CH3AlphaS', 
        'herwig7CH3MPISettings', 
        'herwig7StableParticlesForDetector',
        'hw_PSWeights_settings_custom',
        'hw_user_settings'
    ),
    repository = cms.string('${HERWIGPATH}/HerwigDefaults.rpo'),
    run = cms.string('InterfaceMatchboxTest'),
    runModeList = cms.untracked.string('read,run'),
)
